window.DECK_CARD_CATALOG = {
  Crystalline: [
    "absorber", "arcane fortitude", "arcane timer", "arcane wisdom", "armor bandit",
    "armor devourer", "armor forge", "armor of doom", "armor plate", "ascendant",
    "ashes to glory", "bloodrage marauder", "bloodrage", "body conditioning", "body snatch",
    "brainiac", "chaos drain", "chaotic", "claws", "comeback", "coordinated attack",
    "corrosive claws", "crippling blow", "crystal plauge", "crystalline battery pack",
    "deadly tempo", "demon parade", "eco round", "enchanted skill", "energy recycle",
    "energy siphon", "enhanced armor", "evolved claws", "fiery rage", "flaming fist",
    "flowing fortitude", "forbidden armor", "forbidden blood", "forbidden claws",
    "forbidden leap", "forbidden speed", "gluttonous fiend", "grim pendulum", "growth armor",
    "hardened resolve", "heart ravager", "hidden potential", "hidden strike", "hostile takeover",
    "hunt boost", "ironclad body", "jumper", "kill order", "leaper", "light of life",
    "limit break", "lone advantage", "lone suvivor", "magnetic pull", "monthly pass",
    "no retreat", "northern might", "parting gift", "path of survival", "phantom rodent",
    "phantom", "power entity", "rapid healing", "rear assault", "repture", "revitalized",
    "rusher", "second chance", "serum", "shield bash", "shield of renewal", "smoke escape",
    "soul force", "soul siphon", "speed surge", "speed world", "sprinter", "stamp return",
    "stattering leap", "steal", "stronger together", "survival instinct", "the joker",
    "thousand strikes", "timeflash", "toxic claws", "unarmord claws", "unstable mutation",
    "vengeful spirit", "vital force", "vitality boost", "void armor", "war stomp",
    "world annihilator"
  ],
  Superstring: [
    "active skill", "adaptive resilience", "adaptive shield", "adaptive weapon", "ammo bearer",
    "ammo burst", "amulet", "armorer", "ascend to glory", "assailant", "assasin", "athlete",
    "awaken 1+2", "awaken 1+3", "basic enhancement", "battery pack", "battle cry",
    "battle dancer", "battle drills", "beacon of hope", "berserker", "blade master", "bouncy shot",
    "bounty hunter", "bruiser", "bullet blaze", "card valuation", "chrono bullets", "corrosive shots",
    "crimson demise", "crippler", "crystal analyzer", "crystalline torment", "dark note",
    "defense first", "defensive stance", "demonblade", "dimensional magazine", "dimensional slash",
    "do or die", "dooms gaze", "drumbstick combo", "elo booster", "enhanced emberspit",
    "enhanced granade", "enhanced ignis", "enhanced shock grenade", "enhanced slow granade",
    "equilibrium", "fatal trigger", "finale shot", "focused fire", "full armor", "fury",
    "genetic lock", "glided escape", "glided protector", "grenadier king", "guardian of hope",
    "hardened paper", "headhunter", "heavy barrage", "heavy hitter", "hit and run", "hunter's log",
    "hydro cannon", "illusion shot", "inner strength", "jump power", "jumper", "kinetic overload",
    "kittys blessing", "lethal reload", "level skip", "lone legend", "lone warrior", "max armor",
    "max hp", "medic rounds", "mobile arsenal", "movement speed", "nimble", "no retreat",
    "out of thin air", "overload concerto", "pain inhibition", "power vacuum", "radiant charge",
    "rapid cooldown", "rapid reload", "razor defense", "ready to compete", "relentless assault",
    "relentless spree", "resurgence", "rodent warrior", "rookie support", "saviors resolve",
    "scope hunt", "shared bond", "spell surge", "starry eyes", "steady aim", "sturdy guard",
    "sunbrust armor", "suppression", "survivalist", "sustained vitality", "swift escape", "takeover",
    "temporal wish", "thorny path", "thunderstrike", "together we stand", "toxic spread",
    "treasure raiders", "ultimate ready!", "unified pulse", "unyielding", "war machine",
    "wariors solitude", "whos the boss", "woodpecker"
  ]
};
